#!/usr/bin/bash
export NIXPKGS_ALLOW_BROKEN=1
nix shell github:klarkc/purs-eval nixpkgs#nodejs nixpkgs#haskellPackages.ghc nixpkgs#w3m --impure --command nix-shell -p haskellPackages.patat -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/96ceff97da009d9605287e70cd20b04409ea30c6.tar.gz --command "patat \"$@\""
